### ISSUE TITLE
Nullable Floats panic

### ISSUE THREAD

**Issue by samolds** [spacemonkeygo/dbx#12]
Floats are working now! but nullable floats panic when generating:
```
panic: unhandled var type "sql.NullFloat64" [recovered]
        panic: unhandled var type "sql.NullFloat64"

goroutine 1 [running]:
panic(0x215e40, 0xc420353b00)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/jawher/mow%2ecli.(*step).run(0xc4200ce090, 0x215e40, 0xc420353b00)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:28 +0xc4
github.com/jawher/mow%2ecli.(*step).run(0xc4200ce150, 0x215e40, 0xc420353b00)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:20 +0xed
github.com/jawher/mow%2ecli.(*step).run(0xc4200ce7e0, 0x215e40, 0xc420353b00)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:20 +0xed
github.com/jawher/mow%2ecli.(*step).callDo.func1(0xc4200ce810, 0x0, 0x0)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:41 +0x5b
panic(0x215e40, 0xc420353b00)
        /usr/local/go/src/runtime/panic.go:458 +0x243
gopkg.in/spacemonkeygo/dbx.v1/code/golang.VarFromField(0xc420179a40, 0xc4201f3e00)
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/code/golang/var.go:88 +0x341
gopkg.in/spacemonkeygo/dbx.v1/code/golang.VarsFromFields(0xc4201a2900, 0xd, 0x10, 0x0, 0x0, 0xc420353ac0)
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/code/golang/var.go:105 +0x6c
gopkg.in/spacemonkeygo/dbx.v1/code/golang.VarFromModel(0xc4201a2880, 0x4)
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/code/golang/var.go:44 +0x48
gopkg.in/spacemonkeygo/dbx.v1/code/golang.CreateFromIR(0xc4201952e0, 0x37a9e0, 0x3acf78, 0x8)
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/code/golang/create.go:38 +0x96
gopkg.in/spacemonkeygo/dbx.v1/code/golang.(*Renderer).renderCreate(0xc420090a20, 0x376460, 0xc4201a5f10, 0xc4201952e0, 0x37a9e0, 0x3acf78, 0x0, 0x1)
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/code/golang/renderer.go:301 +0x49
gopkg.in/spacemonkeygo/dbx.v1/code/golang.(*Renderer).RenderCode(0xc420090a20, 0xc4201a3080, 0xc4201bf2c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x268752, 0x6)
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/code/golang/renderer.go:189 +0x235
main.golangCmd(0x7fff5fbff4a8, 0xd, 0xc420010e00, 0x2, 0x2, 0x0, 0x0, 0x7fff5fbff4b6, 0xf, 0x7fff5fbff4c6, ...)
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/main.go:124 +0x1ec
main.main.func2.1()
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/main.go:72 +0xa0
github.com/jawher/mow%2ecli.(*step).callDo(0xc4200ce810, 0x0, 0x0)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:44 +0x70
github.com/jawher/mow%2ecli.(*step).run(0xc4200ce810, 0x0, 0x0)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:16 +0x43
github.com/jawher/mow%2ecli.(*step).run(0xc4200ce7b0, 0x0, 0x0)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:20 +0xed
github.com/jawher/mow%2ecli.(*step).run(0xc4200ce120, 0x0, 0x0)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:20 +0xed
github.com/jawher/mow%2ecli.(*step).run(0xc4200a3e90, 0x0, 0x0)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/flow.go:20 +0xed
github.com/jawher/mow%2ecli.(*Cmd).parse(0xc42000aa00, 0xc42000c0c0, 0x0, 0x0, 0xc4200a3e90, 0xc4200ce120, 0xc4200ce150, 0xc4200ce030, 0xc4200ce030)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/commands.go:441 +0xb7d
github.com/jawher/mow%2ecli.(*Cmd).parse(0xc42000a900, 0xc42000c0b0, 0x9, 0x9, 0xc4200a3e90, 0xc4200a3e90, 0xc4200ce090, 0xc420010901, 0xc4200ce090)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/commands.go:455 +0x9a4
github.com/jawher/mow%2ecli.(*Cli).parse(0xc4200a3f18, 0xc42000c0b0, 0x9, 0x9, 0xc4200a3e90, 0xc4200a3e90, 0xc4200ce090, 0x4, 0x2)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/cli.go:73 +0xa9
github.com/jawher/mow%2ecli.(*Cli).Run(0xc4200a3f18, 0xc42000c0a0, 0xa, 0xa, 0x18, 0xc420014e70)
        /Users/samolds/work/temporary_go_pkgs/src/github.com/jawher/mow.cli/cli.go:102 +0x14a
main.main()
        /Users/samolds/work/temporary_go_pkgs/src/gopkg.in/spacemonkeygo/dbx.v1/main.go:92 +0x317
src/sm/streetwatch/streetwatchdb/common.go:4: running "dbx.v1": exit status 2
```

**Comment by azdagron** [comment]
Fixed by ff76332a8200a15d030c11ed52989ebbf2da4b7e.
